### ISSUE TITLE
Test failures with newer redis, restify and node v7

### ISSUE THREAD

**Issue by cheempz** [tracelytics/node-traceview#174]
See https://travis-ci.org/tracelytics/node-traceview/builds/174943274 for redis and restify test failures.  

When run against node v7:  
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ npm version
{ traceview: '2.7.2',
  npm: '3.10.9',
  ares: '1.10.1-DEV',
  cldr: '30.0.2',
  http_parser: '2.7.0',
  icu: '58.1',
  modules: '51',
  node: '7.1.0',
  openssl: '1.0.2j',
  tz: '2016g',
  unicode: '9.0',
  uv: '1.10.0',
  v8: '5.4.500.36',
  zlib: '1.2.8' }

$ gulp test:probe:restify
[02:02:08] Using gulpfile /vagrant/gulpfile.js
[02:02:08] Starting 'dist'...
[02:02:08] Finished 'dist' after 1.73 ms
[02:02:08] Starting 'dist/probes'...
[02:02:08] Finished 'dist/probes' after 522 μs
[02:02:08] Starting 'build'...
[02:02:11] Finished 'build' after 3.08 s
[02:02:11] Starting 'test:probe:restify'...


  probes.restify
    1) should forward controller/action
    2) should profile each middleware


  0 passing (138ms)
  2 failing

  1) probes.restify should forward controller/action:
     TypeError: The super constructor to "inherits" must not be null or undefined
      at Object.exports.inherits (util.js:961:11)
      at Object.<anonymous> (node_modules/spdy/lib/spdy/connection.js:86:6)
      at Module.patchedRequire [as require] (dist/require-patch.js:37:28)
      at require (internal/module.js:20:19)

  2) probes.restify should profile each middleware:
     TypeError: The super constructor to "inherits" must not be null or undefined
      at Object.exports.inherits (util.js:961:11)
      at Object.<anonymous> (node_modules/spdy/lib/spdy/connection.js:86:6)
      at Module.patchedRequire [as require] (dist/require-patch.js:37:28)
      at require (internal/module.js:20:19)
```

**Comment by Qard** [comment]
That failure is due to Restify depending on an old version of spdy (1.x) which uses process.EventEmitter, which no longer exists.

https://github.com/indutny/node-spdy/blob/v1.32.5/lib/spdy/connection.js#L86

**Comment by almgwary** [comment]
@Qard  you are right, it solved by using older version of node less than v7
i used node v6.2.2  and it is working now
