### ISSUE TITLE
Could not find liboboe native bindings

### ISSUE THREAD

**Issue by reggi** [tracelytics/node-traceview#175]
```
 Error: Could not locate the bindings file. Tried:
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/build/traceview-bindings.node
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/build/Debug/traceview-bindings.node
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/build/Release/traceview-bindings.node
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/out/Debug/traceview-bindings.node
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/Debug/traceview-bindings.node
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/out/Release/traceview-bindings.node
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/Release/traceview-bindings.node
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/build/default/traceview-bindings.node
 → /Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/compiled/7.2.1/darwin/x64/traceview-bindings.node
    at bindings (/Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview-bindings/index.js:1:99)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/thomas/Desktop/wonder-container/wonder/packages/playground-jest/node_modules/traceview/dist/index.js:13:14)

```

**Comment by dkuebric** [comment]
Hey @reggi, that error can happen if you install the `traceview` node module before you've installed the base libraries for traceview (accomplished by running `install_traceview.sh` with your account access key: http://login.tv.solarwinds.com/install

Can you ensure that the base libraries are installed and accessible `liboboe0`,`liboboe-dev` (or `liboboe-devel` on redhat/centos), and uninstall/reinstall the module to see if that resolves your issue?

**Comment by reggi** [comment]
Thanks for this response, I found a different library that satisfies my needs I'm gonna close this out.

**Comment by dkuebric** [comment]
@reggi no problem, sorry you ran into this rough edge.  Out of curiosity, can I ask what you ended up using?

**Comment by xMTinkerer** [comment]
I ran into this same problem on a new set up of traceview. I signed up for a trial account and went through the node.js set up. The set up page shows the host agent as found, then I added these two lines as the first two in my server.js file:

```javascript
var tv = require('traceview');
tv.traceMode = 'always';
```

But when doing `npm start`, I get this:
```

Could not find liboboe native bindings

 Error: Could not locate the bindings file. Tried:
 → /path/node_modules/traceview-bindings/build/traceview-bindings.node
 → /path/node_modules/traceview-bindings/build/Debug/traceview-bindings.node
 → /path/node_modules/traceview-bindings/build/Release/traceview-bindings.node
 → /path/node_modules/traceview-bindings/out/Debug/traceview-bindings.node
 → /path/node_modules/traceview-bindings/Debug/traceview-bindings.node
 → /path/node_modules/traceview-bindings/out/Release/traceview-bindings.node
 → /path/node_modules/traceview-bindings/Release/traceview-bindings.node
 → /path/node_modules/traceview-bindings/build/default/traceview-bindings.node
 → /path/node_modules/traceview-bindings/compiled/6.11.1/linux/x64/traceview-bindings.node
    at bindings (/path/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/path/node_modules/traceview-bindings/index.js:1:99)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/node_modules/traceview/dist/index.js:13:14)
Listening on port 9988
info: Listening on port 9988
```

This is the output of my `install_appneta.sh`
https://pastebin.com/H2nBPsnc

This is my `package.json`:
```json
{
  "name": "appname",
  "version": "1.0.0",
  "description": "Reaching out to the inky blackness to feed all",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon -e css,ejs,js,json --watch ."
  },
  "author": "me",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.15.2",
    "ejs": "^2.5.5",
    "express": "^4.14.0",
    "nodemon": "^1.11.0",
    "promise": "^7.1.1",
    "traceview": "^2.7.3",
    "winston": "^2.3.0"
  }
}
```

**Comment by adam-hert** [comment]
Hey @xMTinkerer the part of our node module that is mentioned in that error (bindings), is compiled when our module is installed. Could you run `npm uninstall traceview` followed by `npm install traceview` and  provide the output? Also which OS / Distro are you using?

**Comment by xMTinkerer** [comment]
Ah, interesting. I see it now:
```

> traceview-bindings@1.0.11 install /path/node_modules/traceview-bindings
> node build

TraceView oboe library not found, tracing disabled
appname@1.0.0 /path
└─┬ traceview@2.7.3 
  ├── array-flatten@2.1.1 
  ├─┬ continuation-local-storage@3.1.7 
  │ ├── async-listener@0.6.7 
  │ └─┬ emitter-listener@1.0.1 
  │   └── shimmer@1.0.0 
  ├─┬ debug@2.2.0 
  │ └── ms@0.7.1 
  ├── es6-weak-map@2.0.2 
  ├── event-unshift@1.0.0 
  ├─┬ glob@7.1.2 
  │ ├── fs.realpath@1.0.0 
  │ └── inflight@1.0.6 
  ├── minimist@1.2.0 
  ├── shimmer@1.1.0 
  ├── sliced@1.0.1 
  └─┬ traceview-bindings@1.0.11 
    ├── bindings@1.2.1 
    └── nan@2.6.2 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN octoapp@1.0.0 No repository field.
```

This is a Google Cloud Debian environment:
```
Linux host 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
```

**Comment by xMTinkerer** [comment]
Wait, why is it looking for Darwin? I selected Linux in the install page?

**Comment by adam-hert** [comment]
That's just an optional dependency, mostly npm being noisy :)

The error messages can be a bit vague in this part of npm, but there are two things to check:
1. Make sure our oboe library was installed `yum list installed | grep oboe`
2. If liboboe and liboboe-devel are listed, you might be missing the build tools needed to compile the bindings. This could be fixed by installing the development tools package: `sudo yum groupinstall "Development tools"`

**Comment by xMTinkerer** [comment]
This is debian, so I did `apt list | grep oboe` and got this:
```
libapache2-mod-oboe/unknown 1.3.1-jessie1 amd64
libmonoboehm-2.0-1/oldstable 3.2.8+dfsg-10 amd64
libmonoboehm-2.0-1-dbg/oldstable 3.2.8+dfsg-10 amd64
libmonoboehm-2.0-dev/oldstable 3.2.8+dfsg-10 amd64
liboboe-dbg/unknown 1.2.3-jessie1 amd64
liboboe-dev/unknown,now 1.2.3-jessie1 amd64 [installed]
liboboe0/unknown,now 1.2.3-jessie1 amd64 [installed]
mod-oboe-ps/unknown 1.7.30.5-jessie3 amd64
php-oboe/unknown 2.0.1-jessie1 amd64
php-oboe-dbg/unknown 2.0.1-jessie1 amd64
```

I didn't see `liboboe-devel`, so I did `apt-get install build-essential` and re-ran `npm start`, but same error.

**Comment by adam-hert** [comment]
I've been spending too much time in CentOS lately.. Now that you have installed build-essential, can you uninstall and reinstall the traceview module again? `npm uninstall traceview && npm install traceview`

**Comment by xMTinkerer** [comment]
Nice. Yep, that did it. I'm good now. 
Thanks!
